name: Switch build and release

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      nx:
        description: build Nintendo Switch
        type: boolean

permissions:
  contents: write

jobs:
  build-nx:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        mode: [debug, release]
    
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    container: devkitpro/devkita64

    steps:
      - name: Get current date as package key
        id: cache_key
        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc

      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

      - name: Update xmake repository
        run: xmake repo --update --root && xmake repo -u --root && dkp-pacman -Rs --noconfirm switch-tinyxml2

      - name: Configure xmake and install dependencies
        run: xmake f --yes -p cross -m ${{ matrix.mode }} -a aarch64 --toolchain=devkita64 -vD --root

      - name: Build SimpleModDownloader
        run: xmake -vD --root

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleModDownloader-${{ matrix.mode }}
          path: build/cross/aarch64/${{ matrix.mode }}/SimpleModDownloader.nro

  release-nx:
    needs: build-nx
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: >
            This is an automated release of the **SimpleModDownloader**.
            - Includes both debug and release builds.
          draft: false
          prerelease: false

      - name: Upload Release Asset (Release Mode)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/cross/aarch64/release/SimpleModDownloader.nro
          asset_name: SimpleModDownloader.nro
          asset_content_type: application/octet-stream